
name: Publish Django Docker Image
on: [push]
jobs:
  publish-hello-docker-image:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build the django-backend Docker image
        run: |
          cd backend && docker build . --tag ghcr.io/tomdieu/momo-app-clone:latest
          cd backend && docker run ghcr.io/tomdieu/momo-app-clone:latest
          cd backend && docker push ghcr.io/tomdieu/momo-app-clone:latest
